displayName=Salve Reminder
author=Dazuz
description=Reminds you to use Salve amulet when appropriate.
tags=salve reminder,salve,reminder,amulet,remind
version=2026-06-11
plugins=com.salvereminder.SalveReminderPlugin
build=standard